---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ cookiecutter.app_name }}
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ cookiecutter.app_name }}
  namespaceSelector:
    matchNames:
      - {{ cookiecutter.k8s_namespace }}
  podMetricsEndpoints:
    - port: "http-metrics"
      interval: 30s
