apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.app_name }}
spec:
  template:
    spec:
      containers:
      - name: app
        image: 325310340739.dkr.ecr.us-east-1.amazonaws.com/{{ cookiecutter.app_name }}:placeholder # {"$imagepolicy": "flux-system:{{ cookiecutter.app_name }}-staging"}
