---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.k8s_namespace }}
resources:
  - ../../../impl/{{ cookiecutter.k8s_namespace }}/{{ cookiecutter.app_name }}
  - ingress.yaml
patchesStrategicMerge:
  - dep-patch.yaml
  - vault-patch.yaml
